version: '3'

services:
  php:
    volumes:
      - ./:/srv/symfony:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Linux, you may use a bind-mounted host directory instead
      - ./var:/srv/symfony/var:rw
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/symfony/public:ro

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - 5432:5432
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  # mailer:
  #   image: schickling/mailcatcher
  #   ports: [1025, 1080]
###< symfony/mailer ###
